Repository dailyAuction/project_daily_auction, pull requests merged in 2023-02, with the labels that each got.

#7 패키지 설치 및 tailwindCSS 기본 설정
  client/.eslintignore
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/src/App.css
  client/src/App.test.tsx
  client/src/App.tsx
  client/src/api/temp.ts
  client/src/atoms/temp.ts
  client/src/components/temp/Temp.tsx
  client/src/components/temp/useTemp.ts
  client/src/constants/temp.ts
  client/src/hooks/temp.ts
  client/src/index.css
  client/src/index.tsx
  client/src/logo.svg
  client/src/pages/TempPage.tsx
  client/src/react-app-env.d.ts
  client/src/reportWebVitals.ts
  client/src/router/Router.tsx
  client/src/setupTests.ts
  client/src/styles/index.css
  client/src/types/temp.tsx
  client/tailwind.config.js
  client/tsconfig.json
Labels: Design

#8 Feat/email service
  server/build.gradle
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/dto/MultiResponseDto.java
  server/src/main/java/com/project/dailyAuction/dto/PageDto.java
  server/src/main/java/com/project/dailyAuction/dto/PageInfo.java
  server/src/main/java/com/project/dailyAuction/etcService/EmailService.java
  server/src/main/java/com/project/dailyAuction/etcService/RandomCodeService.java
  server/src/main/java/com/project/dailyAuction/etcService/RandomPasswordService.java
  server/src/test/java/com/project/dailyAuction/EtcService/EtcServiceTest.java
Labels: Back

#12 💄 Design: font 설정, base-layout 수정
  client/src/styles/index.css
Labels: Front, Design

#15 design: 카테고리 버튼
  client/src/components/CategoryBtn/index.tsx
  client/src/pages/TempPage.tsx
Labels: Front, Design

#18 경매상태, 인풋바 퍼블리싱
  client/src/components/Input/index.tsx
  client/src/components/ProductStatus/index.tsx
Labels: Front, Design

#20 헤더 디자인, 각 페이지별 헤더 추가 퍼블리싱
  client/src/components/Header/MainHeader/index.tsx
  client/src/components/Header/SubHeader/index.tsx
  client/src/pages/CategoryPage.tsx
  client/src/pages/DetailPage.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/NoficationPage.tsx
  client/src/pages/PostProductPage.tsx
  client/src/pages/SearchPage.tsx
  client/src/pages/TempPage.tsx
Labels: Front, Feat, Design

#21 chore : categories 상수 생성
  client/src/constants/constants.ts
Labels: Front

#24 design : 헤더와 하단 탭 바 사이 컨텐츠에 적용하는 글로벌 스타일 추가
  client/src/styles/index.css
Labels: Front, Design

#23 Feat/security
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/dailyAuction.main.iml
  .idea/project_daily_auction.iml
  .idea/vcs.xml
  server/build.gradle
  server/src/main/java/com/project/dailyAuction/Main/MainController.java
  server/src/main/java/com/project/dailyAuction/code/ExceptionCode.java
  server/src/main/java/com/project/dailyAuction/code/MemberStatusCode.java
  server/src/main/java/com/project/dailyAuction/dto/SearchDto.java
  server/src/main/java/com/project/dailyAuction/member/controller/MemberController.java
  server/src/main/java/com/project/dailyAuction/member/dto/MemberDto.java
  server/src/main/java/com/project/dailyAuction/member/entity/Member.java
  server/src/main/java/com/project/dailyAuction/member/mapper/MemberMapper.java
  server/src/main/java/com/project/dailyAuction/member/repository/MemberRepository.java
  server/src/main/java/com/project/dailyAuction/member/service/MemberService.java
  server/src/main/java/com/project/dailyAuction/response/ErrorResponse.java
  server/src/main/java/com/project/dailyAuction/security/config/SecurityConfig.java
  server/src/main/java/com/project/dailyAuction/security/dto/LoginDto.java
  server/src/main/java/com/project/dailyAuction/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/project/dailyAuction/security/filter/JwtVerificationFilter.java
  server/src/main/java/com/project/dailyAuction/security/handler/LoginFailureHandler.java
  server/src/main/java/com/project/dailyAuction/security/handler/LoginSuccessHandler.java
  server/src/main/java/com/project/dailyAuction/security/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/project/dailyAuction/security/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/project/dailyAuction/security/handler/OAuthLoginSuccessHandler.java
  server/src/main/java/com/project/dailyAuction/security/jwt/JwtTokenizer.java
  server/src/main/java/com/project/dailyAuction/security/service/ErrorResponder.java
  server/src/main/java/com/project/dailyAuction/security/service/OAuth2Provider.java
  server/src/main/java/com/project/dailyAuction/security/service/UserDetailsServiceImpl.java
  server/src/main/resources/application.properties
Labels: Back, Feat

#26 Test/board
  server/build.gradle
  server/src/main/java/com/project/dailyAuction/board/Dto/BoardDto.java
  server/src/main/java/com/project/dailyAuction/board/Mapper/BoardMapper.java
  server/src/main/java/com/project/dailyAuction/board/controller/BoardController.java
  server/src/main/java/com/project/dailyAuction/board/entity/Board.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/boardImage/entity/BoardImage.java
  server/src/main/java/com/project/dailyAuction/boardImage/repository/BoardImageRepository.java
  server/src/main/java/com/project/dailyAuction/boardImage/service/ImageHandler.java
  server/src/main/java/com/project/dailyAuction/boardMember/entity/BoardMember.java
  server/src/main/java/com/project/dailyAuction/boardMember/repository/BoardMemberRepository.java
  server/src/main/java/com/project/dailyAuction/code/ExceptionCode.java
  server/src/main/java/com/project/dailyAuction/member/entity/Member.java
  server/src/test/java/com/project/dailyAuction/board/controller/BoardControllerTest.java
Labels: Back, Feat

#25 남은시간, 상품목록 아이템 이미지 퍼블리싱
  client/src/components/ProductItemImg/index.tsx
  client/src/components/TimeRemain/index.tsx
Labels: Front, Design

#28 제품 상세페이지 1차 레이아웃 완료
  client/src/atoms/modalStateAtom.ts
  client/src/components/DetailPage/AuctionStatus/index.tsx
  client/src/components/DetailPage/BidInformation/index.tsx
  client/src/components/DetailPage/Chart/index.tsx
  client/src/components/DetailPage/ImageList/ImageModat.tsx
  client/src/components/DetailPage/ImageList/index.tsx
  client/src/constants/temp.ts
  client/src/mock/productDetail.ts
  client/src/pages/DetailPage.tsx
  client/src/router/Router.tsx
  client/src/styles/index.css
Labels: Front, Design

#29 카테고리 상품 리스트 페이지 작성
  client/package-lock.json
  client/package.json
  client/src/components/CategoryBtn/index.tsx
  client/src/components/CategoryList/index.tsx
  client/src/components/CategoryPageBtn/index.tsx
  client/src/pages/CategoryPage.tsx
  client/src/pages/CategoryProductListPage.tsx
  client/src/router/Router.tsx
Labels: Front, Design

#30 [FE] 상품목록 아이템 퍼블리싱
  client/package-lock.json
  client/package.json
  client/src/components/ ProductItem/index.tsx
  client/tailwind.config.js
Labels: Front, Design

#31 Feat/member service
  server/src/main/java/com/project/dailyAuction/DailyAuctionApplication.java
  server/src/main/java/com/project/dailyAuction/board/Dto/BoardDto.java
  server/src/main/java/com/project/dailyAuction/board/Mapper/BoardMapper.java
  server/src/main/java/com/project/dailyAuction/board/entity/Board.java
  server/src/main/java/com/project/dailyAuction/board/repository/BoardRepository.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/code/ExceptionCode.java
  server/src/main/java/com/project/dailyAuction/etcService/EmailService.java
  server/src/main/java/com/project/dailyAuction/member/controller/MemberController.java
  server/src/main/java/com/project/dailyAuction/member/dto/MemberDto.java
  server/src/main/java/com/project/dailyAuction/member/entity/Member.java
  server/src/main/java/com/project/dailyAuction/member/mapper/MemberMapper.java
  server/src/main/java/com/project/dailyAuction/member/service/MemberService.java
  server/src/main/java/com/project/dailyAuction/security/filter/JwtAuthenticationFilter.java
Labels: Back, Feat

#35 상품 상세페이지 이미지 모달, 캐러셀, 입찰 모달 구현
  client/src/components/DetailPage/AuctionStatus/index.tsx
  client/src/components/DetailPage/BidInformation/index.tsx
  client/src/components/DetailPage/ImageList/ImageModat.tsx
  client/src/components/DetailPage/ImageList/index.tsx
  client/src/components/DetailPage/ImageList/useClickCarousel.tsx
  client/src/constants/constants.ts
  client/src/mock/productDetail.ts
  client/src/pages/DetailPage.tsx
  client/src/styles/index.css
Labels: Front, Feat, Design

#37 [FE] 알림 페이지 퍼블리싱
  client/src/components/DetailPage/AuctionStatus/index.tsx
  client/src/components/DetailPage/BidInformation/index.tsx
  client/src/components/NotificationPage/Notification/index.tsx
  client/src/components/NotificationPage/Notification/useNotification.ts
  client/src/components/TabBar/index.tsx
  client/src/constants/constants.ts
  client/src/mock/notificationResp.ts
  client/src/pages/NoficationPage.tsx
Labels: Front, Feat, Design

#40 refactor: status->statusId
  server/src/main/java/com/project/dailyAuction/board/Dto/BoardDto.java
  server/src/main/java/com/project/dailyAuction/board/Mapper/BoardMapper.java
  server/src/main/java/com/project/dailyAuction/board/entity/Board.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
Labels: Back, Refactor

#41 [FE] 검색 페이지 구현
  client/src/components/CategoryBtn/index.tsx
  client/src/components/SearchPage/TopSearchKeywords/index.tsx
  client/src/components/SearchQuery/index.tsx
  client/src/components/SearchQuery/useSearchQuery.ts
  client/src/mock/topSearchedKeywordResp.ts
  client/src/pages/SearchPage.tsx
  client/src/styles/index.css
Labels: Front, Feat, Design

#42 [FE] 상품등록페이지 퍼블리싱
  client/src/components/RegisterProductPage/CategoryDropdown/index.tsx
  client/src/components/RegisterProductPage/RegisterItemImg/index.tsx
  client/src/components/RegisterProductPage/RegisterProductInfo/index.tsx
  client/src/pages/RegisterProductPage.tsx
  client/src/router/Router.tsx
Labels: Front, Design

#47 비밀번호 변경 페이지 추가
  client/src/components/EditPassword/index.tsx
  client/src/components/MyPageInfo/index.tsx
  client/src/pages/EditPasswordPage.tsx
  client/src/router/Router.tsx
Labels: Front, Design

#52 [#51] 충전 페이지 디자인
  client/src/components/ChargePage/Charge/Charge.tsx
  client/src/components/MyPage/MyPageInfo/MyPageInfo.tsx
  client/src/constants/constants.ts
  client/src/pages/ChargePage.tsx
  client/src/router/Router.tsx
  client/src/styles/index.css
Labels: Front, Design

#53 검색 결과페이지 퍼블리싱, productItem컴포넌트 props 데이터 등 수정
  client/src/atoms/loginStateAtom.ts
  client/src/atoms/modalStateAtom.ts
  client/src/atoms/temp.ts
  client/src/atoms/user.ts
  client/src/components/DetailPage/AuctionStatus/AuctionStatus.tsx
  client/src/components/DetailPage/BidInformation/BidInformation.tsx
  client/src/components/LoginPage/Login/Login.tsx
  client/src/components/MyPage/MyPageInfo/MyPageInfo.tsx
  client/src/components/NotificationPage/Notification/Notification.tsx
  client/src/components/SearchResultPage/SearchResultList/SearchResultList.tsx
  client/src/components/_common/ ProductItem/ProductItem.tsx
  client/src/components/_common/ProductItemImg/ProductItemImg.tsx
  client/src/components/_common/SearchQuery/SearchQuery.tsx
  client/src/components/_common/SearchQuery/useSearchQuery.ts
  client/src/components/_common/TabBar/TabBar.tsx
  client/src/hooks/temp.ts
  client/src/hooks/useGetQueryString.ts
  client/src/hooks/useIsMatchUserId.ts
  client/src/mock/product.ts
  client/src/mock/productDetail.ts
  client/src/pages/DetailPage.tsx
  client/src/pages/SearchResultPage.tsx
  client/src/types/product.type.tsx
  client/src/types/temp.tsx
  client/src/utils/getShortString.ts
Labels: Front, Feat, Design

#56 feat : 인기검색어 검색 기능 추가
  client/src/components/SearchPage/TopSearchKeywords/TopSearchKeywords.tsx
Labels: Front, Feat

#57 [FE] 메인페이지 퍼블리싱
  client/package-lock.json
  client/package.json
  client/src/components/MainPage/Banner/Banner.tsx
  client/src/components/MainPage/BestProduct/BestProduct.tsx
  client/src/components/MainPage/ClosingProduct/ClosingProduct.tsx
  client/src/components/MainPage/Footer/Footer.tsx
  client/src/components/MainPage/ToList/ToList.tsx
  client/src/components/RegisterProductPage/RegisterItemImg/RegisterItemImg.tsx
  client/src/components/_common/Header/MainHeader/MainHeader.tsx
  client/src/pages/MainPage.tsx
  client/src/router/Router.tsx
  client/tailwind.config.js
Labels: Front, Design

#60 [FE] 내등록경매, 내참여경매 페이지 퍼블리싱
  client/src/components/MainPage/ClosingProduct/ClosingProduct.tsx
  client/src/components/MyPage/MyAuctionBtn/MyAuctionBtn.tsx
  client/src/components/MyPage/MyAuctionContent/MyAuctionContent.tsx
  client/src/components/MyPage/MyAuctionList/MyAuctionList.tsx
  client/src/components/MyPage/MyJoinList/MyJoinList.tsx
  client/src/components/MyPage/MyPageInfo/MyPageInfo.tsx
  client/src/components/_common/ ProductItem/ProductItem.tsx
  client/src/components/_common/ProductItemImg/ProductItemImg.tsx
  client/src/mock/product.ts
  client/src/router/Router.tsx
Labels: Front, Design

#62 [FE] 카테고리 상품 목록 페이지 디자인
  client/src/components/CategoryPage/CategoryPageBtn/CategoryPageBtn.tsx
  client/src/components/_common/CategoryList/CategoryList.tsx
  client/src/constants/constants.ts
  client/src/mock/product.ts
  client/src/pages/CategoryPage.tsx
  client/src/pages/CategoryProductListPage.tsx
  client/src/router/Router.tsx
  client/src/styles/index.css
Labels: Front, Design

#64 남은 시간을 카운팅하는 훅 생성
  client/src/components/DetailPage/AuctionStatus/AuctionStatus.tsx
  client/src/components/SearchPage/TopSearchKeywords/TopSearchKeywords.tsx
  client/src/hooks/useGetTimeRemain.ts
  client/src/hooks/useInterval.ts
  client/src/mock/productDetail.ts
Labels: Front, Feat

#65 로그인 여부 확인하는 함수 생성
  client/src/components/DetailPage/BidInformation/BidInformation.tsx
  client/src/hooks/useHandleIsLogin.ts
  client/src/mock/productDetail.ts
Labels: Front, Feat

#66 [FE] 디자인 추가 및 수정
  client/public/testImg/test1.jpeg
  client/public/testImg/test2.jpg
  client/src/components/MainPage/BestProduct/BestProduct.tsx
  client/src/components/MainPage/Footer/Footer.tsx
  client/src/components/MainPage/ToList/ToList.tsx
  client/src/components/PostProductPage/CategoryDropdown/CategoryDropdown.tsx
  client/src/components/PostProductPage/RegisterBtn/RegisterBtn.tsx
  client/src/components/PostProductPage/RegisterItemImg/RegisterItemImg.tsx
  client/src/components/PostProductPage/RegisterProductInfo/RegisterProductInfo.tsx
  client/src/components/_common/ScrollToTopBtn/ScrollToTopBtn.tsx
  client/src/pages/MainPage.tsx
  client/src/pages/PostProductPage.tsx
  client/src/pages/RegisterProductPage.tsx
  client/src/router/Router.tsx
Labels: Front, Design

#69 [FE] 로그인 페이지 유효성 검사 로직
  client/package-lock.json
  client/package.json
  client/src/components/LoginPage/FindPasswordModal/FindPasswordModal.tsx
  client/src/components/LoginPage/Login/Login.tsx
  client/src/mock/userIdPassword.ts
Labels: Front, Feat

#70 Feat/main page
  server/src/main/java/com/project/dailyAuction/Main/MainController.java
  server/src/main/java/com/project/dailyAuction/Search/dto/KeywordDto.java
  server/src/main/java/com/project/dailyAuction/Search/dto/TopKeywordsDto.java
  server/src/main/java/com/project/dailyAuction/Search/entity/Keyword.java
  server/src/main/java/com/project/dailyAuction/Search/mapper/KeywordMapper.java
  server/src/main/java/com/project/dailyAuction/Search/repository/KeywordRepository.java
  server/src/main/java/com/project/dailyAuction/Search/service/SearchService.java
  server/src/main/java/com/project/dailyAuction/board/Dto/BoardDto.java
  server/src/main/java/com/project/dailyAuction/board/Mapper/BoardMapper.java
  server/src/main/java/com/project/dailyAuction/board/entity/Board.java
  server/src/main/java/com/project/dailyAuction/board/repository/BoardRepository.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/member/entity/Member.java
  server/src/test/java/com/project/dailyAuction/board/controller/BoardControllerTest.java
Labels: Back, Feat

#34 Feat/member service
  server/src/main/java/com/project/dailyAuction/board/Dto/BoardDto.java
  server/src/main/java/com/project/dailyAuction/board/entity/Board.java
  server/src/main/java/com/project/dailyAuction/member/controller/MemberController.java
  server/src/main/java/com/project/dailyAuction/member/service/MemberService.java
Labels: Back, Refactor

#71 feat: Board 카테고리별 Sort 기능 추가
  server/src/main/java/com/project/dailyAuction/board/Mapper/BoardMapper.java
  server/src/main/java/com/project/dailyAuction/board/controller/BoardController.java
  server/src/main/java/com/project/dailyAuction/board/repository/BoardRepository.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
Labels: Back, Feat

#72 fix: bidboard uri 변경("/bidding"->"/{board-id}/bidding")
  server/src/main/java/com/project/dailyAuction/board/Dto/BoardDto.java
  server/src/main/java/com/project/dailyAuction/board/controller/BoardController.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
Labels: Back, Fix

#75 [FE] 메인페이지 로직 작성
  client/src/App.tsx
  client/src/components/MainPage/BestProduct/BestProduct.tsx
  client/src/components/MainPage/ClosingProduct/ClosingProduct.tsx
  client/src/pages/MainPage.tsx
Labels: Front, Feat

#79 [FE] 회원가입 페이지 변경
  client/src/components/LoginPage/Login/Login.tsx
  client/src/components/SignUpPage/SignUp/SignUp.tsx
  client/src/components/SignUpPage/SignUpModal/AuthModal.tsx
  client/src/constants/constants.ts
Labels: Front, Feat, Design

#91 게시글 상세페이지 api 요청 로직
  client/package-lock.json
  client/package.json
  client/src/api/boardsAPI.ts
  client/src/api/searchAPI.ts
  client/src/components/DetailPage/BidInformation/BidInformation.tsx
  client/src/components/DetailPage/BidInformation/useBidInformation.ts
  client/src/components/SearchResultPage/SearchResultList/SearchResultList.tsx
  client/src/hooks/useGetTimeRemain.ts
  client/src/hooks/useInterval.ts
  client/src/mock/boards.json
  client/src/mock/product.ts
  client/src/pages/DetailPage.tsx
  client/src/utils/httpClient.ts
Labels: Front, Feat

#81 [FE] 내등록경매, 내참여경매 로직 작성
  client/.gitignore
  client/src/App.tsx
  client/src/api/bestProductAPI.ts
  client/src/api/closingProductAPI.ts
  client/src/api/myAuctionListAPI.ts
  client/src/components/MainPage/BestProduct/BestProduct.tsx
  client/src/components/MainPage/ClosingProduct/ClosingProduct.tsx
  client/src/components/MyPage/MyAuctionContent/MyAuctionContent.tsx
  client/src/components/MyPage/MyAuctionList/MyAuctionList.tsx
  client/src/components/MyPage/MyJoinList/MyJoinList.tsx
  client/src/components/SearchResultPage/SearchResultList/SearchResultList.tsx
  client/src/components/_common/ProductItem/ProductItem.tsx
  client/src/components/_common/ProductItemImg/ProductItemImg.tsx
  client/src/pages/CategoryProductListPage.tsx
Labels: Front, Feat

#83 feat: 현재가격 레디스에서 불러오는 방식으로 수정
  server/src/main/java/com/project/dailyAuction/board/entity/Board.java
  server/src/main/java/com/project/dailyAuction/board/repository/BoardRepository.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/boardMember/entity/BoardMember.java
  server/src/main/java/com/project/dailyAuction/cache/CacheEvent.java
  server/src/main/java/com/project/dailyAuction/cache/CacheProcessor.java
Labels: Back, Feat

#96 게시글 상세페이지 Chart 적용 및 입찰가 유효성 검사 로직 구현
  client/package-lock.json
  client/package.json
  client/src/api/boardsAPI.ts
  client/src/api/temp.ts
  client/src/atoms/user.ts
  client/src/components/DetailPage/BidInformation/BidInformation.tsx
  client/src/components/DetailPage/BidInformation/useBidInformation.ts
  client/src/components/DetailPage/Chart/Chart.tsx
  client/src/mock/boards.json
  client/src/pages/DetailPage.tsx
  client/src/styles/index.css
  client/src/utils/blockInvalidChar.ts
Labels: Front, Feat

#103 [FE] 회원가입 통신 로직 구현
  client/src/api/signupAPI.ts
  client/src/api/verifyAPI.ts
  client/src/components/SignUpPage/SignUp/SignUp.tsx
  client/src/components/SignUpPage/SignUp/useVerify.ts
  client/src/components/SignUpPage/SignUpModal/AuthModal.tsx
  client/src/types/member.type.tsx
Labels: Front, Feat

#106 [FE] 상품등록페이지 로직작성
  client/src/api/postProductAPI.ts
  client/src/components/PostProductPage/CategoryDropdown/CategoryDropdown.tsx
  client/src/components/PostProductPage/RegisterBtn/RegisterBtn.tsx
  client/src/components/PostProductPage/RegisterItemImg/RegisterItemImg.tsx
  client/src/components/PostProductPage/RegisterProductInfo/RegisterProductInfo.tsx
  client/src/pages/PostProductPage.tsx
Labels: Front, Feat

#112 refactor : useGetTimeRemain 버그 픽스 및 리팩토링
  client/src/hooks/useGetTimeRemain.ts
  client/src/hooks/useInterval.ts
  client/src/mock/boards.json
  client/src/pages/DetailPage.tsx
Labels: Front, Fix, Refactor

#113 Feat/sungwoong/kakao scope
  server/src/main/java/com/project/dailyAuction/security/handler/OAuthLoginSuccessHandler.java
  server/src/main/java/com/project/dailyAuction/security/service/OAuth2Provider.java
  server/src/main/resources/application-server.yml
Labels: Back, Fix

#114 feat: notice 알림 추가(코드리뷰반영)
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/cache/CacheConfig.java
  server/src/main/java/com/project/dailyAuction/cache/CacheProcessor.java
  server/src/main/java/com/project/dailyAuction/code/ExceptionCode.java
  server/src/main/java/com/project/dailyAuction/notice/NoticeResponseDto.java
  server/src/main/java/com/project/dailyAuction/notice/NoticeService.java
Labels: Back, Feat

#108 Feat/sungwoong/main to redis
  server/src/main/java/com/project/dailyAuction/Search/service/SearchService.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/cache/CacheEvent.java
  server/src/main/java/com/project/dailyAuction/cache/CacheProcessor.java
Labels: Back, Feat

#115 게시글 상세페이지 웹소켓 로직 작성 / 검색페이지 api 연결
  client/package-lock.json
  client/package.json
  client/src/api/searchAPI.ts
  client/src/components/DetailPage/BidInformation/BidInformation.tsx
  client/src/components/DetailPage/BidInformation/BidModal.tsx
  client/src/components/DetailPage/BidInformation/useBidInformation.ts
  client/src/components/DetailPage/Chart/Chart.tsx
  client/src/components/DetailPage/ImageList/ImageList.tsx
  client/src/components/SearchPage/TopSearchKeywords/TopSearchKeywords.tsx
  client/src/components/SearchResultPage/SearchResultList/SearchResultList.tsx
  client/src/hooks/useWebsocket.ts
  client/src/pages/DetailPage.tsx
  client/src/pages/SearchPage.tsx
  client/src/types/product.type.tsx
Labels: Front, Feat

#120 feat: image awsS3 업로드 기능 적용
  server/build.gradle
  server/src/main/java/com/project/dailyAuction/board/Dto/BoardDto.java
  server/src/main/java/com/project/dailyAuction/board/controller/BoardController.java
  server/src/main/java/com/project/dailyAuction/board/entity/Board.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/boardImage/repository/BoardImageRepository.java
  server/src/main/java/com/project/dailyAuction/boardImage/service/ImageHandler.java
  server/src/main/java/com/project/dailyAuction/notice/NoticeResponseDto.java
Labels: Back, Feat

#121 Feat/sungwoong/redisdelete
  server/src/main/java/com/project/dailyAuction/cache/CacheEvent.java
  server/src/main/java/com/project/dailyAuction/cache/CacheProcessor.java
  server/src/main/java/com/project/dailyAuction/member/dto/MemberDto.java
  server/src/main/java/com/project/dailyAuction/member/mapper/MemberMapper.java
Labels: Back, Fix, Feat

#124 Fix/sungwoong/fix price&time
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/security/config/SecurityConfig.java
Labels: Back, Fix

#125 feat: server-image awsconfig추가
  server/src/main/java/com/project/dailyAuction/board/config/Awsconfig.java
Labels: Back, Feat

#127 Feat/sungwoong/ws error message
  server/src/main/java/com/project/dailyAuction/board/Dto/BoardDto.java
  server/src/main/java/com/project/dailyAuction/board/controller/BoardController.java
  server/src/main/java/com/project/dailyAuction/webSocket/BidController.java
  server/src/main/java/com/project/dailyAuction/webSocket/Message.java
Labels: Back, Test

#126 [FE] 일반 로그인 로직 구현
  client/src/api/loginAPI.ts
  client/src/api/signupAPI.ts
  client/src/api/verifyAPI.ts
  client/src/atoms/localStorageEffect.ts
  client/src/atoms/token.ts
  client/src/atoms/user.ts
  client/src/components/LoginPage/FindPasswordModal/FindPasswordModal.tsx
  client/src/components/LoginPage/Login/Login.tsx
  client/src/components/MyPage/MyPageInfo/MyPageInfo.tsx
  client/src/components/MyPage/MyPageInfo/SignOutModal.tsx
  client/src/components/SignUpPage/SignUp/SignUp.tsx
  client/src/components/SignUpPage/SignUp/useVerify.ts
Labels: Front, Feat

#128 [FE] 로그아웃시 로그인 상태 변경
  client/src/components/MyPage/MyPageInfo/MyPageInfo.tsx
Labels: Front, Fix, Feat

#129 [FE] 메인페이지 추가작업
  client/public/testImg/test2.jpeg
  client/public/testImg/test2.jpg
  client/public/testImg/test3.jpeg
  client/src/api/bestProductAPI.ts
  client/src/api/closingProductAPI.ts
  client/src/api/mainPageAPI.ts
  client/src/api/myAuctionListAPI.ts
  client/src/api/myPageAPI.ts
  client/src/components/MainPage/Banner/Banner.tsx
  client/src/components/MainPage/BestProduct/BestProduct.tsx
  client/src/components/MainPage/ClosingProduct/ClosingProduct.tsx
  client/src/components/MyPage/MyAuctionContent/MyAuctionContent.tsx
  client/src/components/MyPage/MyAuctionList/MyAuctionList.tsx
  client/src/components/MyPage/MyJoinList/MyJoinList.tsx
  client/src/components/_common/ProductItem/ProductItem.tsx
  client/src/components/_common/ProductItemImg/ProductItemImg.tsx
  client/src/components/_common/TimeRemain/TemiRemain.tsx
Labels: Front, Feat

#130 feat: 조회수 중복처리 - 쿠키
  server/src/main/java/com/project/dailyAuction/board/controller/BoardController.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/boardMember/repository/BoardMemberRepository.java
Labels: Back, Feat

#136 [FE] 회원가입 로직 구현
  client/src/api/signupAPI.ts
  client/src/components/SignUpPage/SignUp/SignUp.tsx
  client/src/components/SignUpPage/SignUp/useVerify.ts
  client/src/components/SignUpPage/SignUpModal/AuthModal.tsx
  client/src/components/_common/Modal/SuccessModal.tsx
Labels: Front, Feat

#134 Refactor/sungwoong/details
  server/src/main/java/com/project/dailyAuction/board/controller/BoardController.java
  server/src/main/java/com/project/dailyAuction/board/dto/BoardDto.java
  server/src/main/java/com/project/dailyAuction/board/entity/Board.java
  server/src/main/java/com/project/dailyAuction/board/mapper/BoardMapper.java
  server/src/main/java/com/project/dailyAuction/board/mapper/BoardMapping.java
  server/src/main/java/com/project/dailyAuction/board/repository/BoardRepository.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/boardMember/repository/BoardMemberRepository.java
  server/src/main/java/com/project/dailyAuction/code/BoardStatusCode.java
  server/src/main/java/com/project/dailyAuction/main/MainController.java
  server/src/main/java/com/project/dailyAuction/member/controller/MemberController.java
  server/src/main/java/com/project/dailyAuction/member/mapper/MemberMapper.java
  server/src/main/java/com/project/dailyAuction/member/service/MemberService.java
  server/src/main/java/com/project/dailyAuction/notice/NoticeResponseDto.java
  server/src/main/java/com/project/dailyAuction/webSocket/BidController.java
  server/src/test/java/com/project/dailyAuction/board/controller/BoardControllerTest.java
Labels: Back, Style, Refactor

#132 refactor: api명세랑 네이밍 통일
  server/src/main/java/com/project/dailyAuction/board/dto/BoardDto.java
  server/src/main/java/com/project/dailyAuction/board/mapper/BoardMapper.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/member/controller/MemberController.java
  server/src/main/java/com/project/dailyAuction/member/service/MemberService.java
Labels: Back, Refactor

#133 Feat/sungwoong/return board
  server/src/main/java/com/project/dailyAuction/board/controller/BoardController.java
  server/src/main/java/com/project/dailyAuction/board/dto/BoardDto.java
  server/src/main/java/com/project/dailyAuction/cache/CacheProcessor.java
  server/src/main/java/com/project/dailyAuction/main/MainController.java
  server/src/main/java/com/project/dailyAuction/search/dto/TopKeywordsDto.java
  server/src/main/java/com/project/dailyAuction/search/entity/Keyword.java
  server/src/main/java/com/project/dailyAuction/search/mapper/KeywordMapper.java
  server/src/main/java/com/project/dailyAuction/search/repository/KeywordRepository.java
  server/src/main/java/com/project/dailyAuction/search/service/SearchService.java
Labels: Back, Feat

#139 Feat/sungwoong/redis
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/cache/CacheProcessor.java
Labels: Back, Fix, Refactor

#140 Feat/be notice sse
  server/src/main/java/com/project/dailyAuction/board/dto/BoardDto.java
  server/src/main/java/com/project/dailyAuction/board/entity/Board.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/member/entity/Member.java
  server/src/main/java/com/project/dailyAuction/notice/NoticeResponseDto.java
Labels: Back, Feat

#138 Refactor/sungwoong/member status
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/cache/CacheProcessor.java
  server/src/main/java/com/project/dailyAuction/code/BoardStatusCode.java
  server/src/main/java/com/project/dailyAuction/code/MemberStatusCode.java
  server/src/main/java/com/project/dailyAuction/code/NoticeStatusCode.java
  server/src/main/java/com/project/dailyAuction/member/entity/Member.java
  server/src/main/java/com/project/dailyAuction/member/mapper/MemberMapper.java
Labels: Back, Feat, Refactor

#141 feat: 소셜로그인 시 회원상태 업데이트
  server/src/main/java/com/project/dailyAuction/member/controller/MemberController.java
  server/src/main/java/com/project/dailyAuction/member/service/MemberService.java
Labels: Back, Feat

#131 웹소켓으로 입찰 요청 구현, 유저의 판매,입찰 여부에 따른 상태메시지 로직 수정
  client/src/components/DetailPage/AuctionStatus/AuctionStatus.tsx
  client/src/components/DetailPage/AuctionStatus/useAuctionStatus.ts
  client/src/components/DetailPage/BidInformation/BidInformation.tsx
  client/src/components/DetailPage/BidInformation/BidModal.tsx
  client/src/components/DetailPage/BidInformation/useBidInformation.ts
  client/src/components/DetailPage/Chart/Chart.tsx
  client/src/components/DetailPage/ImageList/ImageList.tsx
  client/src/hooks/useWebsocket.ts
  client/src/pages/DetailPage.tsx
  client/src/pages/NoficationPage.tsx
  client/src/types/product.type.tsx
Labels: Front, Fix, Feat

#142 [FE] 코인 충전 로직 구현
  client/src/api/coinAPI.ts
  client/src/components/ChargePage/Charge/Charge.tsx
  client/src/components/ChargePage/Charge/useCharge.ts
  client/src/components/ChargePage/ChargeModal/CheckModal.tsx
  client/src/components/MyPage/MyPageInfo/MyPageInfo.tsx
  client/src/constants/constants.ts
  client/src/hooks/useCoinCalc.ts
Labels: Front, Feat, Chore

#145 Refactor/sungwoong/develop
  server/src/main/java/com/project/dailyAuction/board/controller/BoardController.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/cache/CacheEvent.java
  server/src/main/java/com/project/dailyAuction/cache/CacheProcessor.java
  server/src/main/java/com/project/dailyAuction/webSocket/BidController.java
Labels: Back, Feat, Refactor

#146 차트 실시간 데이터 렌더링, 하단 탭 바 로그인 페이지 렌더링 수정
  client/src/components/DetailPage/Chart/Chart.tsx
  client/src/components/_common/TabBar/TabBar.tsx
  client/src/pages/DetailPage.tsx
Labels: Fix, Feat

#147 feat: 마감된 글에 입찰 불가
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/code/ExceptionCode.java
Labels: Back, Feat

#149 fix: 알림status별로 response에 기입되는 contact다르게 수정
  server/src/main/java/com/project/dailyAuction/notice/Notice.java
  server/src/main/java/com/project/dailyAuction/notice/NoticeService.java
Labels: Back, Fix

#148 Refactor/sungwoong/develop
  server/src/main/java/com/project/dailyAuction/cache/CacheEvent.java
  server/src/main/java/com/project/dailyAuction/cache/CacheProcessor.java
  server/src/main/java/com/project/dailyAuction/search/service/SearchService.java
  server/src/main/java/com/project/dailyAuction/security/handler/LoginFailureHandler.java
  server/src/main/java/com/project/dailyAuction/security/handler/LoginSuccessHandler.java
  server/src/main/java/com/project/dailyAuction/security/handler/MemberAccessDeniedHandler.java
  server/src/main/java/com/project/dailyAuction/security/handler/MemberAuthenticationEntryPoint.java
  server/src/main/java/com/project/dailyAuction/security/handler/OAuthLoginSuccessHandler.java
  server/src/main/java/com/project/dailyAuction/security/jwt/JwtTokenizer.java
Labels: Back, Refactor

#150 fix: statusCode로 변경해서 기입
  server/src/main/java/com/project/dailyAuction/notice/NoticeService.java
Labels: Back, Fix

#151 [FE] 페이지 작동확인 및 버그수정
  client/src/api/myPageAPI.ts
  client/src/api/postProductAPI.ts
  client/src/components/DetailPage/AuctionStatus/useAuctionStatus.ts
  client/src/components/MyPage/MyAuctionContent/MyAuctionContent.tsx
  client/src/components/MyPage/MyAuctionList/MyAuctionList.tsx
  client/src/components/MyPage/MyJoinList/MyJoinList.tsx
  client/src/components/PostProductPage/CategoryDropdown/CategoryDropdown.tsx
  client/src/components/PostProductPage/RegisterBtn/RegisterBtn.tsx
  client/src/components/PostProductPage/RegisterItemImg/RegisterItemImg.tsx
  client/src/components/_common/ProductItem/ProductItem.tsx
  client/src/pages/PostProductPage.tsx
Labels: Front, Feat

#153 fix: createdAt->createdAtAfter로 수정
  server/src/main/java/com/project/dailyAuction/board/repository/BoardRepository.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
Labels: Back, Fix

#154 SSE연결, 입찰/재등록 버튼 보이도록 수정
  client/package-lock.json
  client/package.json
  client/src/components/DetailPage/BidInformation/BidInformation.tsx
  client/src/components/DetailPage/ImageList/ImageList.tsx
  client/src/components/_common/Header/MainHeader/MainHeader.tsx
  client/src/pages/DetailPage.tsx
  client/src/pages/NoficationPage.tsx
  client/src/types/product.type.tsx
Labels: Front, Fix

#156 [FE] 비밀번호 변경 구현
  client/src/api/coinAPI.ts
  client/src/api/editPasswordAPI.ts
  client/src/components/ChargePage/Charge/Charge.tsx
  client/src/components/ChargePage/ChargeModal/CheckModal.tsx
  client/src/components/EditPasswordPage/EditPassword/EditPassword.tsx
  client/src/components/MyPage/MyPageInfo/MyPageInfo.tsx
  client/src/components/SignUpPage/SignUp/SignUp.tsx
  client/src/components/_common/Modal/SuccessModal.tsx
  client/src/components/_common/OpenPassword/OpenPassword.tsx
  client/src/constants/constants.ts
Labels: Front, Feat, Chore

#155 fix: 서버 재실행시 가격 반영없이 삭제하는 버그 수정
  server/src/main/java/com/project/dailyAuction/cache/CacheEvent.java
Labels: Back, Fix

#158 Feat/sungwoong/add seller email
  server/src/main/java/com/project/dailyAuction/board/dto/BoardDto.java
  server/src/main/java/com/project/dailyAuction/board/mapper/BoardMapper.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/member/controller/MemberController.java
  server/src/main/java/com/project/dailyAuction/security/handler/OAuthLoginSuccessHandler.java
Labels: Back, Feat

#160 feat: 마이페이지 응답데이터에 멤버아이디 추가
  server/src/main/java/com/project/dailyAuction/member/dto/MemberDto.java
  server/src/main/java/com/project/dailyAuction/member/service/MemberService.java
Labels: Back, Feat

#157 [FE] 회원탈퇴 API 및 구현
  client/package-lock.json
  client/package.json
  client/src/api/signoutAPI.ts
  client/src/components/MyPage/MyPageInfo/SignOutModal.tsx
Labels: Front, Feat, Chore

#161 myPage API 요청 로직 및 기타 수정
  client/src/api/myPageAPI.ts
  client/src/atoms/user.ts
  client/src/components/DetailPage/BidInformation/BidModal.tsx
  client/src/components/DetailPage/BidInformation/useBidInfoModal.ts
  client/src/components/DetailPage/BidInformation/useBidInformation.ts
  client/src/hooks/useWebsocket.ts
  client/src/types/member.type.tsx
Labels: Front, Feat, Refactor

#162 Feat/sungwoong/sse setting change
  server/src/main/java/com/project/dailyAuction/notice/EmitterRepositoryImpl.java
  server/src/main/java/com/project/dailyAuction/notice/NoticeService.java
  server/src/main/java/com/project/dailyAuction/support/DatasourceConfig.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
Labels: Back

#163 Fix/sungwoong/details
  server/src/main/java/com/project/dailyAuction/board/repository/BoardRepository.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/security/handler/OAuthLoginSuccessHandler.java
  server/src/main/java/com/project/dailyAuction/webSocket/BidController.java
Labels: Back, Fix

#164 Fix/sungwoong/details
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/cache/CacheEvent.java
  server/src/main/java/com/project/dailyAuction/cache/CacheProcessor.java
Labels: Back, Fix

#165 SSE 알림 수신 기능 구현
  client/src/components/ChargePage/Charge/useCharge.ts
  client/src/components/DetailPage/BidInformation/BidModal.tsx
  client/src/components/DetailPage/BidInformation/useBidInfoModal.ts
  client/src/components/_common/Header/MainHeader/MainHeader.tsx
  client/src/hooks/useSSE.ts
Labels: Front, Fix, Feat
