Repository dailyAuction/project_daily_auction, pull requests merged in 2023-03, with the labels that each got.

#170 fix: 같은 사람 연속 입찰 못하는 검증 추가
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/code/ExceptionCode.java
Labels: Back, Fix

#172 fix: 모든 페이지에서 가격정보 레디스에서 가져오게 수정
  server/src/main/java/com/project/dailyAuction/board/controller/BoardController.java
  server/src/main/java/com/project/dailyAuction/board/mapper/BoardMapper.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/main/MainController.java
  server/src/main/java/com/project/dailyAuction/member/controller/MemberController.java
Labels: Back, Fix

#171 [FE] 이미지압축, 아이폰 이미지 변환, 기타 수정
  client/package-lock.json
  client/package.json
  client/src/components/MainPage/BestProduct/BestProduct.tsx
  client/src/components/MainPage/ClosingProduct/ClosingProduct.tsx
  client/src/components/MyPage/MyAuctionList/MyAuctionList.tsx
  client/src/components/MyPage/MyJoinList/MyJoinList.tsx
  client/src/components/PostProductPage/RegisterBtn/RegisterBtn.tsx
  client/src/components/PostProductPage/RegisterItemImg/RegisterItemImg.tsx
  client/src/components/_common/ProductItem/ProductItem.tsx
  client/src/components/_common/ProductItemImg/ProductItemImg.tsx
  client/src/components/_common/TabBar/TabBar.tsx
  client/src/pages/PostProductPage.tsx
  client/src/types/product.type.tsx
Labels: Front, Feat

#175 게시글 상세페이지 입찰 후 데이터 업데이트 수정
  client/src/api/boardsAPI.ts
  client/src/components/DetailPage/AuctionStatus/useAuctionStatus.ts
  client/src/components/DetailPage/BidInformation/BidInformation.tsx
  client/src/components/DetailPage/BidInformation/BidModal.tsx
  client/src/components/DetailPage/BidInformation/useBidInfoModal.ts
  client/src/hooks/useGetProductDetail.ts
  client/src/hooks/useWebsocket.ts
  client/src/pages/DetailPage.tsx
Labels: Front, Fix, Feat

#176 [FE] 카테고리 페이지 구현
  client/src/api/categoryAPI.ts
  client/src/components/_common/CategoryList/CategoryList.tsx
  client/src/constants/constants.ts
  client/src/pages/CategoryProductListPage.tsx
Labels: Front, Feat

#174 fix: thumbnail 오류 수정
  server/src/main/java/com/project/dailyAuction/boardImage/service/ImageHandler.java
Labels: Back, Fix

#178 Fix/sungwoong/last member
  server/src/main/java/com/project/dailyAuction/board/mapper/BoardMapper.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/member/controller/MemberController.java
Labels: Back, Fix

#180 검색 및 인기 검색어 기능 구현
  client/src/api/searchAPI.ts
  client/src/components/SearchPage/TopSearchKeywords/TopSearchKeywords.tsx
  client/src/components/SearchResultPage/SearchResultList/SearchResultList.tsx
  client/src/types/product.type.tsx
Labels: Front, Fix, Feat

#181 입찰 이후 모달창 바로 닫히도록 수정
  client/src/components/DetailPage/BidInformation/BidInformation.tsx
  client/src/components/DetailPage/BidInformation/BidModal.tsx
  client/src/components/DetailPage/BidInformation/useBidInfoModal.ts
Labels: Front, Feat

#183 fix: 초단위 00초로 고정
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/member/service/MemberService.java
Labels: Back, Fix

#182 Refactor/be local
  server/src/main/java/com/project/dailyAuction/board/controller/BoardController.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/member/service/MemberService.java
  server/src/main/java/com/project/dailyAuction/webSocket/BidController.java
Labels: Back, Refactor

#184 SSE 실시간 알림 수신 및 렌더링
  client/src/App.tsx
  client/src/components/NotificationPage/Notification/Notification.tsx
  client/src/components/NotificationPage/Notification/useNotification.ts
  client/src/components/_common/Header/MainHeader/MainHeader.tsx
  client/src/components/_common/SSE/SSE.tsx
  client/src/constants/constants.ts
  client/src/hooks/useNotification.ts
  client/src/hooks/useSSE.ts
  client/src/pages/NoficationPage.tsx
  client/src/types/notice.type.tsx
Labels: Front, Feat

#185 Feat/be notice sse
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/cache/CacheProcessor.java
  server/src/main/java/com/project/dailyAuction/member/entity/Member.java
  server/src/main/java/com/project/dailyAuction/notice/controller/NoticeController.java
  server/src/main/java/com/project/dailyAuction/notice/dto/NoticeResponseDto.java
  server/src/main/java/com/project/dailyAuction/notice/entity/Notice.java
  server/src/main/java/com/project/dailyAuction/notice/mapper/NoticeMapper.java
  server/src/main/java/com/project/dailyAuction/notice/repository/EmitterRepository.java
  server/src/main/java/com/project/dailyAuction/notice/repository/EmitterRepositoryImpl.java
  server/src/main/java/com/project/dailyAuction/notice/repository/NoticeRepository.java
  server/src/main/java/com/project/dailyAuction/notice/service/NoticeService.java
Labels: Back, Feat

#186 fix: 쿠키 도메인 설정
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
Labels: Back, Fix

#188 [FE] 인터셉터 구현
  client/src/components/MyPage/MyPageInfo/MyPageInfo.tsx
  client/src/components/MyPage/MyPageInfo/SignOutModal.tsx
  client/src/hooks/useResetUserInfo.ts
  client/src/utils/httpClient.ts
Labels: Front, Feat

#187 알림 조회/삭제, 헤더 상태 변경, 기타 버그 수정
  client/src/api/boardsAPI.ts
  client/src/api/noticesAPI.ts
  client/src/components/DetailPage/BidInformation/useBidInfoModal.ts
  client/src/components/DetailPage/BidInformation/useBidInformation.ts
  client/src/components/LoginPage/Login/Login.tsx
  client/src/components/NotificationPage/Notification/Notification.tsx
  client/src/components/_common/Header/MainHeader/MainHeader.tsx
  client/src/components/_common/SSE/SSE.tsx
  client/src/constants/constants.ts
  client/src/hooks/useNotification.ts
  client/src/hooks/useSSE.ts
  client/src/pages/NoficationPage.tsx
Labels: Front, Fix, Feat

#189 [FE] 무한스크롤, 기타수정
  client/package-lock.json
  client/package.json
  client/src/api/mainPageAPI.ts
  client/src/api/myPageAPI.ts
  client/src/components/MainPage/BestProduct/BestProduct.tsx
  client/src/components/MainPage/ClosingProduct/ClosingProduct.tsx
  client/src/components/MainPage/ToList/ToList.tsx
  client/src/components/MyPage/MyAuctionBtn/MyAuctionBtn.tsx
  client/src/components/MyPage/MyAuctionContent/MyAuctionContent.tsx
  client/src/components/MyPage/MyAuctionList/MyAuctionList.tsx
  client/src/components/MyPage/MyJoinList/MyJoinList.tsx
  client/src/components/_common/Loading/Loading.tsx
  client/src/components/_common/ProductItem/ProductItem.tsx
  client/src/components/_common/ScrollToTopBtn/ScrollToTopBtn.tsx
  client/src/pages/MainPage.tsx
  client/src/router/Router.tsx
Labels: Front, Feat

#193 Refactor/be
  server/src/main/java/com/project/dailyAuction/DailyAuctionApplication.java
  server/src/main/java/com/project/dailyAuction/board/controller/BoardController.java
  server/src/main/java/com/project/dailyAuction/board/entity/Board.java
  server/src/main/java/com/project/dailyAuction/board/mapper/BoardMapper.java
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
  server/src/main/java/com/project/dailyAuction/boardImage/service/ImageHandler.java
  server/src/main/java/com/project/dailyAuction/boardMember/repository/BoardMapping.java
  server/src/main/java/com/project/dailyAuction/boardMember/repository/BoardMemberRepository.java
  server/src/main/java/com/project/dailyAuction/cache/CacheEvent.java
  server/src/main/java/com/project/dailyAuction/cache/CacheProcessor.java
  server/src/main/java/com/project/dailyAuction/code/BoardStatusCode.java
  server/src/main/java/com/project/dailyAuction/code/ExceptionCode.java
  server/src/main/java/com/project/dailyAuction/code/MemberStatusCode.java
  server/src/main/java/com/project/dailyAuction/code/NoticeStatusCode.java
  server/src/main/java/com/project/dailyAuction/dto/MultiResponseDto.java
  server/src/main/java/com/project/dailyAuction/dto/PageDto.java
  server/src/main/java/com/project/dailyAuction/dto/PageInfo.java
  server/src/main/java/com/project/dailyAuction/etcService/EmailService.java
  server/src/main/java/com/project/dailyAuction/etcService/RandomCodeService.java
  server/src/main/java/com/project/dailyAuction/etcService/RandomPasswordService.java
  server/src/main/java/com/project/dailyAuction/main/MainController.java
  server/src/main/java/com/project/dailyAuction/member/controller/MemberController.java
  server/src/main/java/com/project/dailyAuction/member/entity/Member.java
  server/src/main/java/com/project/dailyAuction/member/mapper/MemberMapper.java
  server/src/main/java/com/project/dailyAuction/member/service/MemberService.java
  server/src/main/java/com/project/dailyAuction/notice/controller/NoticeController.java
  server/src/main/java/com/project/dailyAuction/notice/mapper/NoticeMapper.java
  server/src/main/java/com/project/dailyAuction/notice/repository/EmitterRepository.java
  server/src/main/java/com/project/dailyAuction/notice/repository/EmitterRepositoryImpl.java
  server/src/main/java/com/project/dailyAuction/notice/service/NoticeService.java
  server/src/main/java/com/project/dailyAuction/response/ErrorResponse.java
  server/src/main/java/com/project/dailyAuction/search/entity/Keyword.java
  server/src/main/java/com/project/dailyAuction/search/service/SearchService.java
  server/src/main/java/com/project/dailyAuction/security/config/SecurityConfig.java
  server/src/main/java/com/project/dailyAuction/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/project/dailyAuction/security/handler/OAuthLoginSuccessHandler.java
  server/src/main/java/com/project/dailyAuction/security/jwt/JwtTokenizer.java
  server/src/main/java/com/project/dailyAuction/security/service/UserDetailsServiceImpl.java
  server/src/main/java/com/project/dailyAuction/support/BaseTimeEntity.java
  server/src/main/java/com/project/dailyAuction/support/DatasourceConfig.java
  server/src/main/resources/application-local.yml
  server/src/main/resources/application-server.yml
Labels: Back, Refactor

#192 CSS 버그 픽스 / 코드 분할 적용 / 로딩 컴포넌트 적용
  client/src/components/DetailPage/ImageList/ImageList.tsx
  client/src/components/NotificationPage/Notification/Notification.tsx
  client/src/components/_common/TabBar/TabBar.tsx
  client/src/hooks/useHandleIsLogin.ts
  client/src/hooks/useNotification.ts
  client/src/pages/MainPage.tsx
  client/src/router/Router.tsx
  client/src/styles/index.css
  client/src/utils/lazyImport.ts
  client/tsconfig.json
Labels: Front, Fix

#195 [FE] 기타수정
  client/package-lock.json
  client/package.json
  client/src/components/MainPage/BestProduct/BestProduct.tsx
  client/src/components/MyPage/MyAuctionContent/MyAuctionContent.tsx
  client/src/components/PostProductPage/RegisterBtn/RegisterBtn.tsx
Labels: Front, Feat

#196 meta 태그 추가/배너 이미지 변경
  client/public/favicon.ico
  client/public/favicon/gavel.png
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/components/MainPage/Banner/Banner.tsx
Labels: Front, Fix

#197 버그 수정 : 콘솔 로그, og image, 메인페이지 배경 등
  client/public/index.html
  client/src/App.tsx
  client/src/pages/MainPage.tsx
Labels: Front, Fix

#200 fix : no-explicit-any warning으로 변경
  client/.eslintrc.json
Labels: Front, Fix

#202 hotfix : 삭제된 파일 복구
  client/.eslintignore
  client/.prettierrc.json
  client/README.md
  client/postcss.config.js
  client/public/manifest.json
  client/public/robots.txt
  client/public/socialLogin/google_login.png
  client/public/socialLogin/kakao_login.png
  client/public/testImg/test1.jpeg
  client/src/components/CategoryPage/CategoryPageBtn/CategoryPageBtn.tsx
  client/src/components/DetailPage/ImageList/useClickCarousel.ts
  client/src/components/MainPage/Footer/Footer.tsx
  client/src/components/_common/CategoryBtn/CategoryBtn.tsx
  client/src/components/_common/Header/SubHeader/SubHeader.tsx
  client/src/components/_common/Input/Input.tsx
  client/src/components/_common/ProductStatus/ProductStatus.tsx
  client/src/components/_common/SearchQuery/SearchQuery.tsx
  client/src/components/_common/SearchQuery/useSearchQuery.ts
  client/src/hooks/useGetQueryString.ts
  client/src/hooks/useIsMatchUserId.ts
  client/src/index.tsx
  client/src/mock/notificationResp.ts
  client/src/mock/productDetail.ts
  client/src/mock/topSearchedKeywordResp.ts
  client/src/mock/userIdPassword.ts
  client/src/pages/CategoryPage.tsx
  client/src/pages/ChargePage.tsx
  client/src/pages/EditPasswordPage.tsx
  client/src/pages/LoginPage.tsx
  client/src/pages/MyPage.tsx
  client/src/pages/SearchResultPage.tsx
  client/src/pages/SignUpPage.tsx
  client/src/pages/TempPage.tsx
  client/src/utils/getShortString.ts
  client/tailwind.config.js
Labels: Front, Fix

#207 CSS 수정 : 스크롤바 제거, 여백 추가, 버튼 변경
  client/src/components/DetailPage/ImageList/ImageList.tsx
  client/src/components/MyPage/MyPageInfo/MyPageInfo.tsx
  client/src/pages/CategoryProductListPage.tsx
  client/src/pages/MainPage.tsx
Labels: Front, Fix

#209 Fix/bug fix0311
  server/src/main/java/com/project/dailyAuction/cache/CacheProcessor.java
  server/src/main/java/com/project/dailyAuction/code/ExceptionCode.java
  server/src/main/java/com/project/dailyAuction/member/service/MemberService.java
  server/src/main/java/com/project/dailyAuction/search/service/SearchService.java
Labels: Back, Fix

#210 feat: 목업데이터 매일 등록
  server/src/main/java/com/project/dailyAuction/board/service/BoardService.java
Labels: Back, Feat

#211 [FE] 에러 해결 - 로그인시 정보가 맞지 않을 경우
  client/src/utils/httpClient.ts
Labels: Front, Fix

#216 [FE] 터치스크롤, 버그픽스
  client/src/components/MainPage/BestProduct/BestProduct.tsx
  client/src/components/MainPage/ClosingProduct/ClosingProduct.tsx
  client/src/components/PostProductPage/RegisterBtn/RegisterBtn.tsx
  client/src/components/PostProductPage/RegisterItemImg/RegisterItemImg.tsx
  client/src/hooks/useGetTimeRemain.ts
  client/src/hooks/useTouchScroll.ts
Labels: Front, Fix, Feat

#217 [FE] 로컬 스토리지 관련 hook 구현
  client/src/atoms/localStorageEffect.ts
  client/src/hooks/useLocalStorage.ts
  client/src/utils/httpClient.ts
Labels: Front, Fix, Feat
